name: direction
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.2+3

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  iconsax: ^0.0.8
  iconly: ^1.0.1
  auto_size_text: ^3.0.0
  razorpay_flutter: ^1.3.5
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.0
  pull_down_button: ^0.10.1
  in_app_purchase: ^3.2.0
  get_ip_address: ^0.0.7
  ip_country_lookup: ^1.0.3
  internet_connection_checker_plus: ^2.5.2
  lottie: ^3.1.2
  flutter_bloc: ^8.1.6
  amplitude_flutter: ^3.13.0
  dio: ^5.7.0
  equatable: ^2.0.5
  firebase_analytics: ^11.3.3
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  cached_network_image: ^3.4.1
  zego_zimkit: ^1.18.13



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.0
  rename: ^3.0.2

flutter_launcher_icons:
  ios: true
  android: false
  image_path: "asset/images/png/only_logo.png"
  remove_alpha_ios: true

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - asset/images/jpg/
    - asset/images/png/
    - asset/images/svg/
    - asset/images/lottie/

  fonts:
    - family: gilroy_extra_bold
      fonts:
        - asset: asset/fonts/gilroy/gilroy_extra_bold.otf

    - family: gilroy_light
      fonts:
        - asset: asset/fonts/gilroy/gilroy_light.otf
